/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Kotlin.Unit.Test.app

class MessageUtils {
    companion object {
//        define function
        fun getMessage(): String = "Hello      World!"
        fun sayHello(): String = "Hello Reihan!!"
    }
}
