/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Kotlin.Gradle.app

class MessageUtils {
    companion object {
        fun getMessage(): String = "Hello      World!"
    }


}
